"""Central configuration for Arespath Rover.

Optimized v5:
─────────────
• 50 Hz control loop for smoother motor response
• No blocking delays anywhere
• WebSocket-based map updates
• Clear workflow: PILOT → MAPPING → WAYPOINTS → MISSION

All tuneable constants live here — change values here, not scattered
through the codebase.
"""
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
MAPS_DIR = BASE_DIR / "maps"
DATA_DIR = BASE_DIR / "data"
SNAPSHOT_DIR = BASE_DIR / "snapshots"
PHOTOS_DIR = BASE_DIR / "photos"

MAPS_DIR.mkdir(exist_ok=True, parents=True)
DATA_DIR.mkdir(exist_ok=True, parents=True)
SNAPSHOT_DIR.mkdir(exist_ok=True, parents=True)
PHOTOS_DIR.mkdir(exist_ok=True, parents=True)

WHEEL_RADIUS_M = 0.060
WHEEL_BASE_M = 0.400

ENCODER_MODEL = "OE-37"
ENCODER_PPR = 11
ENCODER_QUADRATURE = 4
MOTOR_GEAR_RATIO = 30.0
TICKS_PER_WHEEL_REV = float(ENCODER_PPR * ENCODER_QUADRATURE * MOTOR_GEAR_RATIO)

MAX_PWM = 180
MAX_LINEAR_MPS = 0.40
MAX_ANGULAR_RADPS = 1.5
OBSTACLE_STOP_DISTANCE_M = 0.35
OBSTACLE_WAIT_BEFORE_REPLAN_S = 5.0
OBSTACLE_REPLAN_REVERSE_S = 0.8
OBSTACLE_REVERSE_SPEED = -0.35

ROVER_LENGTH_M = 0.520
ROVER_WIDTH_M = 0.500
ROVER_HEIGHT_M = 0.300
WHEEL_DIAMETER_M = 0.120
WHEEL_TRACK_M = 0.400
LIDAR_OFFSET_X_M = 0.240
LIDAR_OFFSET_Y_M = 0.000
DEFAULT_SPEED_PCT = 55

CONTROL_HZ = 20.0
MANUAL_COMMAND_TIMEOUT_S = 0.4
TELEMETRY_TIMEOUT_S = 1.5
HEARTBEAT_TIMEOUT_S = 3.0
WATCHDOG_IDLE_S = 0.5
NAV_REPLAN_SECONDS = 2.0
WAYPOINT_REACHED_M = 0.20
GOAL_TOLERANCE_M = 0.25
HEADING_TOLERANCE_RAD = 0.25
PATH_LOOKAHEAD_M = 0.30
NAV_LINEAR_GAIN = 0.80
NAV_ANGULAR_GAIN = 1.50
ROTATE_IN_PLACE_THRESHOLD_RAD = 0.9

SERIAL_BAUD = 115200
ARDUINO_SERIAL_PORT = "/dev/ttyUSB0"
SERIAL_CANDIDATES = [
    "/dev/ttyUSB0",
    "/dev/ttyACM0",
    "/dev/ttyACM1",
    "/dev/ttyUSB1",
]

CAMERA_DEVICES: dict = {
    "front": "/dev/video0",
    "rear": "/dev/video2",
}
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
CAMERA_FPS = 15
JPEG_QUALITY = 80
SNAPSHOT_SECONDS = 10
SNAPSHOT_RETENTION_SECONDS = 300

LIDAR_SERIAL_PORT = "/dev/ttyUSB1"
LIDAR_BAUDRATE = 115200
LIDAR_SCAN_FREQUENCY = 6.0
LIDAR_SAMPLE_RATE = 3
LIDAR_SINGLE_CHANNEL = True
LIDAR_MIN_RANGE_M = 0.12
LIDAR_MAX_RANGE_M = 8.0
LIDAR_RENDER_MAX_POINTS = 360

MAP_RESOLUTION_M = 0.02
MAP_SIZE_CELLS = 2400
MAP_ORIGIN_X_M = -24.0
MAP_ORIGIN_Y_M = -24.0
FREE_HIT = -0.5
OCCUPIED_HIT = 2.0
LOG_ODDS_MIN = -5.0
LOG_ODDS_MAX = 5.0
MAP_OCCUPIED_THRESHOLD = 0.68
MAP_FREE_THRESHOLD = 0.32
PLANNER_INFLATION_CELLS = 5

LIDAR_LOCALIZATION_ENABLED = True
LIDAR_ICP_MAX_ITERATIONS = 50
LIDAR_ICP_TOLERANCE_M = 0.001
LIDAR_ICP_MAX_CORRESP_M = 0.40
LIDAR_ICP_WEIGHT = 0.80
LIDAR_ICP_MIN_POINTS = 15
LIDAR_ICP_INTERVAL_S = 0.05

POIS_FILE = DATA_DIR / "pois.json"
RUNTIME_SETTINGS_FILE = DATA_DIR / "runtime_settings.json"

WEB_PORT = 8080
STATUS_POLL_MS = 450
MAP_POLL_MS = 2000
LIDAR_POLL_MS = 260
